name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ ${{ secrets.DO_TOKEN_1 }}, ${{ secrets.DO_TOKEN_2 }} ]

    steps:
      - name: Checkout to project
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ matrix.node }}

      - name: Init droplets
        run: |
          cd ${PWD}/automation/digitaocean
          ./init.sh 2

      - name: Sleep for 300 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '300s'

      - name: Clear droplets
        run: |
          cd automation/digitaocean
          ./clear.sh
