name: Clear-DO-Drippier-Droplets

on:
  workflow_dispatch

jobs:
  clear-3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to project
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN_3 }}

      - name: Clear droplets
        run: |
          cd automation/digitaocean/dripper
          ./clear.sh

  clear-4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to project
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN_4 }}

      - name: Clear droplets
        run: |
          cd automation/digitaocean/dripper
          ./clear.sh

  clear-7:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to project
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN_7 }}

      - name: Clear droplets
        run: |
          cd automation/digitaocean/dripper
          ./clear.sh

  clear-8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to project
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN_8 }}

      - name: Clear droplets
        run: |
          cd automation/digitaocean/dripper
          ./clear.sh
