name: DO-4-Dripper-Max-3

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target'
        required: true
      droplets_count:
        description: 'Droplets Count'
        required: true

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to project
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN_4 }}

      - name: Init droplets
        run: |
          cd ${PWD}/automation/digitaocean/dripper
          ./init.sh ${{ github.event.inputs.droplets_count }} ${{ github.event.inputs.target }}

      - name: Sleep for 3600 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '3600s'

      - name: Clear droplets
        run: |
          cd automation/digitaocean/dripper
          ./clear.sh
