name: Linode

on:
  workflow_dispatch:
    inputs:
      destination:
        description: 'Destination'
        required: true
      duration:
        description: 'Duration in seconds'
        required: true

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to project
        uses: actions/checkout@v2

      - name: Setup Linode cli
        uses: brendon1555/setup-linode-cli@master
        with:
          LINODE_CLI_TOKEN: ${{ secrets.L_TOKEN_1 }}
        run: linode-cli --help

      - name: Init instances
        run: |
          cd ${PWD}/automation/linode
          ./init.sh 10 ${{ secrets.L_SECRET }}

      - name: Sleep for 900 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '900s'

      - name: Clear instances
        run: |
          cd automation/linode
          ./clear.sh
